### ISSUE TITLE
Rename expected storage target `root_path` `job_id` placeholder to `job_name`

### ISSUE THREAD

**Issue by derekocallaghan** [pangeo-forge/pangeo-forge-runner#47]
Runner currently expects/uses a `job_name` parameter, e.g. as specified by the orchestrator. If the corresponding run config storage `root_path` instances contain a `job_name` placeholder, they'll be expanded to use the specified `job_name`. However, although `job_name` is typically used everywhere, this operation tries to expand a `job_id` placeholder:

https://github.com/pangeo-forge/pangeo-forge-runner/blob/480d238cbb334162a907a1c8d1da5a27c50ffc6f/pangeo_forge_runner/storage.py#L52-L57

`job_id` should probably be renamed to `job_name` for consistency. I can create a PR with a test for this.

**Comment by cisaacstern** [comment]
> job_id should probably be renamed to job_name for consistency

I'll defer to @yuvipanda since this is `pangeo-forge-runner` but yes, this seems like a bug. Good catch, @derekocallaghan!

**Comment by derekocallaghan** [comment]
Thanks @cisaacstern. I noticed this while looking into the cache usage across production runs, checking whether previously cached files from failed runs are used in subsequent runs (e.g as I mentioned in the last meeting: https://github.com/pangeo-forge/eooffshore_ics_ccmp_v02_1_nrt_wind-feedstock/issues/2). As `job_name` isn't in any of the bakery config `root_path` values, it looks like the cache is shared between runs. I'd misunderstood this previously, as I assumed there was a separate cache per run.

**Comment by cisaacstern** [comment]
@derekocallaghan, thanks for double-checking this. Now that you've surfaced this snippet, I remember that I did not include job-specific identifiers in the cache `root_path` for precisely this reason: so cached files can be reused across jobs.

`MetadataCacheStorage` cannot be reused, however, so that does [include a per-job `{subpath}`](https://github.com/pangeo-forge/pangeo-forge-orchestrator/blob/fb5caaf6994d1b73004b447ab00e5687ab941f2e/bakeries/pangeo-ldeo-nsf-earthcube.pangeo-forge.yaml#L24-L27).

If you're seeing slow performance on rerunning recipes for which the inputs have already been cached, it may be because computing metadata (for recipes that require it) has to happen every time, and this can certainly be expensive, as it requires opening every single input file with xarray.

As I believe you're aware, but just to state it here for clarity, metadata does not need to be computed at runtime if the input files are all the same length in the concat dim, and the [`nitems_per_file` option](https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_recipes/recipe_user_guide/file_patterns.html#specifying-nitems-per-file-in-a-concatdim) is passed.

**Comment by derekocallaghan** [comment]
Thanks @cisaacstern. In this recipe, I'm using `nitems_per_file` as although the pruned version worked locally without it, it was noticeably faster when I used it. I don't know how far the previous failed production run got, but at least it'll be able to avoid cached data retrieval in future runs.

**Comment by cisaacstern** [comment]
I think https://github.com/pangeo-forge/pangeo-forge-runner/pull/55 might fix this?

**Comment by derekocallaghan** [comment]
> I think #55 might fix this?

Thanks @cisaacstern and @yuvipanda, #55 has fixed it:

https://github.com/pangeo-forge/pangeo-forge-runner/blob/1e1a947923874a8405a8648fe4dccd42c23abdc4/pangeo_forge_runner/storage.py#L52-L57
