### ISSUE TITLE
Enable vertical autoscaling when using prime?

### ISSUE THREAD

**Issue by jbusecke** [pangeo-forge/pangeo-forge-runner#95]
One of the reasons I [want to use dataflow prime](https://github.com/leap-stc/cmip6-leap-feedstock/issues/16) is to avoid OOM situations. If I understand correctly this requires vertical autoscaling to be enabled. AFAICT this is not done from within `-runner`?
Could we add [these flags](https://cloud.google.com/dataflow/docs/vertical-autoscaling#batch) either as additional option or automatically add them when `use_dataflow_prime` is set?

**Comment by cisaacstern** [comment]
Seems reasonable to consider adding those flags.

But for your specific problem @jbusecke, is it possible that:

- the high memory demand jobs are all netcdf3 sources which xarray can't lazily load with the scipy backend
- therefore using OpenWithKerchunk instead of OpenWithXarray would allow lazily access, and save the need for large worker memory allocation, regardless of source file type

?

Asking because this might be cheaper in the end (less memory usage), especially because of the scale you ultimately envision.

And also because your pioneering development eye on using kerchunk for netcdf3 access would be useful for others with the same problem.

**Comment by yuvipanda** [comment]
@jbusecke you can try out https://github.com/pangeo-forge/pangeo-forge-runner/pull/96 to see if that enables it.

**Comment by jbusecke** [comment]
@cisaacstern I think these two things are not mutually exclusive? Ideally I could use prime *and* minimize the memory we need, which would probably result in the least resources used overall? 

Let me try #96 and see how that goes.

**Comment by jbusecke** [comment]
While I am still not sure if vertical autoscaling is enabled, I can report that these jobs seem to work mostly the same as the non-prime ones (many fail during testing - that is fine, and the other failures are similar to the non-prime ones). 
From a first look they might be a bit cheaper, which is nice. Little hard to quantify (will need some dedicated comparisons), but many of these jobs cost about 0.2 DCU, which translates into ~1 cent?
